import img01 from '../images/ny1.jpg';
import img02 from '../images/ny2.jpg';
import img03 from '../images/ny3.jpg';

export const images = [
  {
    name: 'New York',
    link: img01,
    _id: 1,
  },
  {
    name: 'New York',
    link: img02,
    _id: 2,
  },
  {
    name: 'New York',
    link: img03,
    _id: 3,
  },
  {
    name: 'New York',
    link: img01,
    _id: 4,
  },
  {
    name: 'New York',
    link: img02,
    _id: 5,
  },
]

export const flightCards = [
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 1,
    airport: 'VKO',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 2,
    airport: 'VKO',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 3,
    airport: 'VKO',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 4,
    airport: 'VKO',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 5,
    airport: 'VKO',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 6,
    airport: 'VKO',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 7,
    airport: 'VKO',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 8,
    airport: 'VKO',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 9,
    airport: 'VKO',
  },
]