
export const images = [
  {
    name: 'New York',
    link: require('../images/ny4.png'),
    _id: 1,
  },
  {
    name: 'New York',
    link: require('../images/ny5.png'),
    _id: 2,
  },
  {
    name: 'New York',
    link: require('../images/ny4.png'),
    _id: 3,
  },
  {
    name: 'New York',
    link: require('../images/ny5.png'),
    _id: 4,
  },
  {
    name: 'New York',
    link: require('../images/ny4.png'),
    _id: 5,
  },
  {
    name: 'New York',
    link: require('../images/ny5.png'),
    _id: 6,
  },
]

export const flightCards = [
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 1,
    departurePort: 'VKO',
    arrivalPort: 'JFK',
    boarding: '19:20',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 2,
    departurePort: 'VKO',
    arrivalPort: 'JFK',
    boarding: '19:20',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 3,
    departurePort: 'VKO',
    arrivalPort: 'JFK',
    boarding: '19:20',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 4,
    departurePort: 'VKO',
    arrivalPort: 'JFK',
    boarding: '19:20',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 5,
    departurePort: 'VKO',
    arrivalPort: 'JFK',
    boarding: '19:20',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 6,
    departurePort: 'VKO',
    arrivalPort: 'JFK',
    boarding: '19:20',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 7,
    departurePort: 'VKO',
    arrivalPort: 'JFK',
    boarding: '19:20',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 8,
    departurePort: 'VKO',
    arrivalPort: 'JFK',
    boarding: '19:20',
  },
  {
    departure: 'Moscow',
    arrival: 'New York',
    date: '28 June, 2020',
    time: '14:50',
    airlines: 'Aeroflot',
    price: '23 924 ₽',
    _id: 9,
    departurePort: 'VKO',
    arrivalPort: 'JFK',
    boarding: '19:20',
  },
]